version: '3'

services:

  api:
    image: turbolent/postgrest-alpine
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGRST_SERVER_HOST=${PGRST_SERVER_HOST:-*6}
      - PGRST_SERVER_PORT=${PGRST_SERVER_PORT:-3000}
      - PGRST_DB_POOL=${PGRST_DB_POOL:-100}
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=${PGRST_DB_SCHEMA:-public}
      - PGRST_SERVER_PROXY_URI=${PGRST_SERVER_PROXY_URI:-http://localhost:3000/}
      - PGRST_SECRET_IS_BASE64=${PGRST_SECRET_IS_BASE64:-false}
      - PGRST_JWT_AUD=${PGRST_JWT_AUD}
      - PGRST_MAX_ROWS=${PGRST_MAX_ROWS}
      - PGRST_PRE_REQUEST=${PGRST_PRE_REQUEST}
      - PGRST_DB_ANON_ROLE
      - PGRST_JWT_SECRET

  db:
    image: andreychuk/postgres-pgjwt
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    command: postgres -c app.jwt_secret=${PGRST_JWT_SECRET} -c app.jwt_duration=${PGRST_JWT_DURATION:-3600}
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/

  swagger-ui:
    image: swaggerapi/swagger-ui:3.15.0
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3000/
    restart: always
